---
  # Common prereqs (e.g. build tools, libs)
  - include: common-prereqs.yml

  - include: rbenv-setup.yml
    when: ruby.install
    sudo: yes
    sudo_user: "{{ ruby.deploy_user }}"

  # Installing required ruby versions
  - include: rbenv-install.yml ruby_version={{ version }}
    when: ruby.install
    sudo: yes
    sudo_user: "{{ ruby.deploy_user }}"

  # Configuring ruby environment (e.g. setting the defaut ruby)
  - include: rbenv-configure.yml ruby_version={{ version }}
    when: ruby.install
    sudo: yes
    sudo_user: "{{ ruby.deploy_user }}"

  # Common ruby environment tasks (e.g. adding a .gemrc, ...)
  - include: common-post.yml
    sudo: yes
    sudo_user: "{{ ruby.deploy_user }}"

