# Installing required ruby versions
- include: ruby-install.yml version={{ ruby_versions }}
  become: yes
  become_user: "{{ ruby_deploy_user }}"

# Common ruby environment tasks (e.g. adding a .gemrc, ...)
- include: common-post.yml
  become: yes
  become_user: "{{ ruby_deploy_user }}"

