#
# NOTE: Replace ruby.version by version when parametric works..
#
    - name: Ruby | Checks if target ruby is installed
      action: shell cd; bash -lc "rbenv versions | grep {{ ruby_version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '"
#      action: shell bash -c "export HOME=/home/{{ ruby.deploy_user }}; source ~/.bashrc; rbenv versions | grep {{ ruby_version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '"
      register: ruby_is_installed
      tags:
        - ruby
        - ruby:install
        - install

    - name: Ruby | Installs ruby
      action: shell cd; bash -lc "rbenv install {{ ruby_version }}"
      when: ruby_is_installed.stdout != ruby_version
      # Takes no more than 600 secs on a small VM
      async: 600
      poll: 30
      tags:
        - ruby
        - ruby:install
        - install

